### ISSUE TITLE
can i help me

### ISSUE THREAD

**Issue by ts19970816** [FLming/CRNN.tf2#31]
Epoch 1/20
2022-02-16 08:42:18.888733: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 1 of dimension 0 out of bounds.
2022-02-16 08:42:18.888759: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 1 of dimension 0 out of bounds.
2022-02-16 08:42:18.888775: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 1 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "crnn/train.py", line 59, in <module>
    validation_data=val_ds)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3040, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1964, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  slice index 1 of dimension 0 out of bounds.
	 [[node strided_slice_1 (defined at crnn/train.py:59) ]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
	 [[OptionalHasValue_1/_12]]
  (1) Invalid argument:  slice index 1 of dimension 0 out of bounds.
	 [[node strided_slice_1 (defined at crnn/train.py:59) ]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_12630]

Function call stack:
train_function -> train_function

**Comment by FLming** [comment]
Please provide more information

**Comment by ts19970816** [comment]
tensorflow                         2.6.2
cuda 11.1
cudnn 8.0.5

**Comment by FLming** [comment]
With the current information, I can't help much either. It just say "Invalid argument: slice index 1 of dimension 0 out of bounds.". Please provide some background.
